### ISSUE TITLE
Save trained model

### ISSUE THREAD

**Issue by B87** [signaflo/java-timeseries#22]
Hi, thanks for your implementation it has been very useful for me.

I just wanna know if there is a way to save an ARIMA model on disk for future predictions.

**Comment by signaflo** [comment]
@B87, there's nothing specific to this library to make that possible. I would personally use [GSON](https://github.com/google/gson) because it's easy to use, especially when working with immutable objects as many of this library's objects are. I'll see if I can get a working example together.

**Comment by Inqus** [comment]
> @B87, there's nothing specific to this library to make that possible. I would personally use [GSON](https://github.com/google/gson) because it's easy to use, especially when working with immutable objects as many of this library's objects are. I'll see if I can get a working example together.

Since the Arima class is an interface, it is not possible to recreate the model object from the json string

```java
 Arima model  = gson.fromJson(new FileReader("models/model_1.json"), Arima.class);
```

ArimaModel class is final...

```java
Exception in thread "main" java.lang.RuntimeException: Unable to invoke no-args constructor for interface com.github.signaflo.timeseries.model.arima.Arima. Registering an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:870)
	at arima.Predict.predict(Predict.java:51)
	at arima.Predict.main(Predict.java:27)
Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: com.github.signaflo.timeseries.model.arima.Arima
	at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117)
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
	... 5 more
```

I also can’t save ArimaOrder, when I try to save I get an empty file without errors
```java
 ArimaOrder modelOrder = ArimaOrder.order(0, 1, 1, 0, 1, 1); 
Gson gson = new Gson();
gson.toJson(modelOrder, new FileWriter("models/model_1.json"));
```
