### ISSUE TITLE
Many errors upon initial build

### ISSUE THREAD

**Issue by dgcui1225** [signaflo/java-timeseries#23]
I don't think this is supposed to happen; when I try to build java-timeseries-master after forking and downloading it, I get a ton of build errors before I've actually touched anything. 
![screen shot 2018-07-11 at 2 16 27 pm](https://user-images.githubusercontent.com/17695277/42599734-180f778c-8515-11e8-9354-8c828de3a953.png)

**Comment by signaflo** [comment]
@dgcui1225 , you're right, that definitely shouldn't be happening. I think something like that this has happened to me before and it had to do with either Java/Gradle versioning. If you can give me as much detail as possible about how you're executing the build process, I might be able to help.

**Comment by signaflo** [comment]
@dgcui1225 , I've updated some of the build files and it's working for me (off the master branch). Let me know if you continue to run into issues.

**Comment by dgcui1225** [comment]
It works for me, thank you very much!

**Comment by MuhYusuf93** [comment]
@dgcui1225 I was try to build my aplication, and i have error same with you. May you give me the solve of this error?

**Comment by MuhYusuf93** [comment]
anybody help me please... :(

**Comment by Wafflemannauto** [comment]
Is is possible that lombook needs to know what setters and getter should be injected?

I generated those missing methods and the "//"s of uncommented methods were removed.
Additionally, I added following constructor:
ArimaParameters(double[] numAR, double[]numMA, double[] numSAR, double[] numSMA) {
        this.autoRegressivePars = numAR;
        this.movingAveragePars = numMA;
        this.seasonalAutoRegressivePars = numSAR;
        this.seasonalMovingAveragePars = numSMA;
    }
	
Then all test except two pass. I've also tried to copy the given arrays but this doesn't change the result (in my case).

junit.framework.AssertionFailedError: Range: 1.0 to 3.0 by 1.0 [group 1, item 1] must be Object#equals to Range: 1.0 to 3.0 by 1.0 [group 1, item 2]
	at com.google.common.testing.RelationshipTester.assertWithTemplate(RelationshipTester.java:125)
	at com.google.common.testing.RelationshipTester.assertRelated(RelationshipTester.java:101)
	at com.google.common.testing.RelationshipTester.test(RelationshipTester.java:77)
	at com.google.common.testing.EqualsTester.testEquals(EqualsTester.java:119)
	at com.github.signaflo.data.RangeSpec.equalsContract(RangeSpec.java:210)
	
junit.framework.AssertionFailedError: com.github.signaflo.data.regression.MultipleLinearRegressionModel@12843fce [group 1, item 1] must be Object#equals to com.github.signaflo.data.regression.MultipleLinearRegressionModel@3dd3bcd [group 1, item 2]
	at com.google.common.testing.RelationshipTester.assertWithTemplate(RelationshipTester.java:125)
	at com.google.common.testing.RelationshipTester.assertRelated(RelationshipTester.java:101)
	at com.google.common.testing.RelationshipTester.test(RelationshipTester.java:77)
	at com.google.common.testing.EqualsTester.testEquals(EqualsTester.java:119)
	at com.github.signaflo.data.regression.LinearRegressionSpec.equalsContract(LinearRegressionSpec.java:130)
